/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AmountDue: typeof import('./src/components/organisms/amountDue.vue')['default']
    Bill: typeof import('./src/components/dash_comp/Bill.vue')['default']
    Bookings: typeof import('./src/components/dash_comp/Bookings.vue')['default']
    Button: typeof import('primevue/button')['default']
    Clients: typeof import('./src/components/dash_comp/clients.vue')['default']
    ClubStats: typeof import('./src/components/dash_comp/ClubStats.vue')['default']
    CreateSession: typeof import('./src/components/dash_comp/CreateSession.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    Finances: typeof import('./src/components/dash_comp/Finances.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Invoice: typeof import('./src/components/dash_comp/Invoice.vue')['default']
    LineChart: typeof import('./src/components/organisms/LineChart.vue')['default']
    LoginForm: typeof import('./src/components/organisms/loginForm.vue')['default']
    Navbar: typeof import('./src/components/organisms/navbar.vue')['default']
    NewClass: typeof import('./src/components/organisms/newClass.vue')['default']
    Overview: typeof import('./src/components/dash_comp/Overview.vue')['default']
    PayBill: typeof import('./src/components/organisms/PayBill.vue')['default']
    PaymentForm: typeof import('./src/components/organisms/PaymentForm.vue')['default']
    RecentClient: typeof import('./src/components/dash_comp/RecentClient.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TopClient: typeof import('./src/components/dash_comp/TopClient.vue')['default']
    TotalSession: typeof import('./src/components/dash_comp/TotalSession.vue')['default']
    UpcomingClasses: typeof import('./src/components/dash_comp/UpcomingClasses.vue')['default']
    UpcomingSession: typeof import('./src/components/dash_comp/UpcomingSession.vue')['default']
    UserStats: typeof import('./src/components/dash_comp/UserStats.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
